fix: Spinbutton day tests
w3c/aria-practices pull request #1640
Opened 2020-12-01 06:58 UTC by nschonni

2020-12-01 07:00 UTC, nschonni commented
/cc @spectranaut @mcking65

2020-12-01 07:08 UTC, mcking65 commented
Thank you @nschonni 
I'd like to have @spectranaut take a look

2020-12-01 16:54 UTC, spectranaut requested changes
thanks so much for the fixes to downarrow! But I don't think we should fix the failing tests related to page down and page up -- those tests are failing because the example code is incorrect, as is tracked in issue #1426. We don't want to have tests that pass because they don't run into the bug that currently exists in the example.

Can you revert the changes to page up/page down in this PR?

2020-12-01 18:03 UTC, nschonni commented
@spectranaut I've updated the spec and test to reflect the current behaviour, then #1426 can be used to update it to the new behaviour

2020-12-01 18:16 UTC, spectranaut approved these changes
As long as Matt is ok with the change in the description of the `page up`/`page down` on the spin button, then I approve this PR.

2020-12-01 18:18 UTC, nschonni commented
@spectranaut feel free to cherry pick part of the fix into #1639 if you think this might be slower to land and want to get the test green quicker 😄

2020-12-01 22:00 UTC, spectranaut commented
I cherry picked the first commit (`Fix: Down arrow test`) into this PR: https://github.com/w3c/aria-practices/pull/1639

So if you could drop it from this PR we can consider the rest of the changes :)

2020-12-01 22:12 UTC, nschonni commented
👍 when that one lands I'll rebase and it'll drop out. If i remove it now, the tests will fail 😄 . Although because of the GitHub Actions issues earlier today, there are a bunch of failures right now

2020-12-03 03:32 UTC, mcking65 commented
Based on above comments and commits in #1639, I merged that one. Do we still need something from this PR?

2020-12-03 04:03 UTC, nschonni commented
@mcking65 the other PR had just the first commit from this PR, now gone because I rebased. The rest of the commits took a similar approach to enable the other tests marked failing and updated the example description to match the current behaviour. The flip side to these changes is that @spectranaut opened the issue #1426 because the current behaviour might not be what is wanted in the future.

2020-12-03 22:40 UTC, spectranaut commented
It would be nice to get some eyes on this change -- what is the preferred way for the spin button date picker to behave at month and year boundaries with "page up" and "page down"? Should it always move the spinner 5 up or 5 down? Or, once you get to within 5 of the last day or first day of the month, should it just jump the last or first day of the month?

What do you think, @carmacleod, @jongund ?

2020-12-04 02:57 UTC, nschonni commented
Opened #1653 as an alternate approach to change the rollover behaviour

2020-12-04 15:34 UTC, jongund commented
@spectranaut @carmacleod 
I think the buttons should not roll over, e.g. when increasing it should stop at the maximum value, when decreasing it should stop at the minimum value.

2021-01-10 03:26 UTC, mcking65 commented
@jongund commented:

> I think the buttons should not roll over, e.g. when increasing it should stop at the maximum value, when decreasing it should stop at the minimum value.


If we are going to change the behavior, let's make that a different issue and PR. Personally, in date pickers, I kind of like the ones where increasing the value just rolls time forward across boundaries, e.g., increasing day on Jan 31 changes date to Feb 1. However, stopping at boundaries is just as valid.

Jon, if you think we should have a discussion of the behavior, please raise an issue.

I'm going to go ahead with this PR so we at least have documentation and testing that matches the current behavior.

2021-01-10 04:07 UTC, mcking65 requested changes
Thank you @nschonni!

I'd like to merge, but have some editorial suggestions to simplify the language.

2021-01-10 04:07 UTC, mcking65 commented on examples/spinbutton/datepicker-spinbuttons.html
> +                <li>When focus is on the <q>Day</q> spin button and the value is the last day of the month or any of the last four days, changes value to the first day of the month.</li>
```suggestion
                <li>When focus is on the <q>Day</q> spin button and the value is any of the last five days of the month, changes value to the first day of the month.</li>
```

2021-01-10 04:07 UTC, mcking65 commented on examples/spinbutton/datepicker-spinbuttons.html
> +                <li>When focus is on the <q>Month</q> spin button and the value is <q>December</q>, <q>November</q>, <q>October</q>, <q>September</q>, or <q>August</q>, changes value to <q>January</q
```suggestion
                <li>When focus is on the <q>Month</q> spin button and the value is any of the last five months of the year, changes value to <q>January</q>.</li>
```

2021-01-10 04:33 UTC, mcking65 approved these changes
Thank you, ready to ship now!

2021-01-10 04:40 UTC, merged