Combobox: add tests for backspace
w3c/aria-practices pull request #1645
Opened 2020-12-02 01:34 UTC by spectranaut

This PR is https://github.com/w3c/aria-practices/pull/1363 with some code review comments implemented and master merged into the branch and conflicts resolved!

2020-12-19 01:22 UTC, jugglinmike requested changes
`npm run regression-report` is failing on the `master` branch. This makes it harder to understand if the pull request is regressing. It turns out that this one is not, so the problem is out of scope for this patch. I'm mentioning it anyway in hopes that it gets on someone's radar.

I've verified that the tests pass. I could probably give more input, but I'm out of time for the day!

2020-12-21 19:13 UTC, spectranaut commented on test/tests/combobox_autocomplete-both.js
> +    await assertAttributeValues(t, ex.textboxSelector, 'aria-expanded', 'true');
Thanks for that catch, @jugglinmike! fixed :)

2020-12-21 19:14 UTC, spectranaut commented
hi @mcking65 -- This PR was originally @zcorpan work so I reviewed it when I adopted it, and Mike took a look (though he only got part way through).  I think it's good to go, in that it has been looked at by me, @zcorpan and @jugglinmike

2020-12-22 00:45 UTC, mcking65 commented
Hurray, someone fixed the W3C payment plan issue with Travis and our Travis no-op job is passing again!

2020-12-22 00:48 UTC, merged