Add deprecation warning to Collapsible Listbox example
w3c/aria-practices pull request #1852
Opened 2021-04-09 18:14 UTC by smhigley

Resolves #657

Includes the following two changes:
- Updates the link on the main aria-practices.html page to point to the select-only combobox with a text note
- Adds a deprecation warning to the listbox example page

2021-04-09 19:29 UTC, carmacleod commented on examples/listbox/listbox-collapsible.html
> +    <p><strong>DEPRECATION WARNING:</strong> this pattern has been deprecated, and will be removed in a future version of the Authoring Practices. The <a href="../combobox/combobox-select-only.html">
I would add ARIA (or WAI-ARIA) as follows:

```suggestion
    <p><strong>DEPRECATION WARNING:</strong> this pattern has been deprecated, and will be removed in a future version of the ARIA Authoring Practices. The <a href="../combobox/combobox-select-only.html">select-only combobox</a> should be used as an alternative to this pattern.</p>
```

2021-04-09 19:31 UTC, carmacleod approved these changes
Looks good!
Thanks, @smhigley !
Approving whether or not the little suggested change is included.

2021-04-26 05:14 UTC, mcking65 commented
@smhigley 

The deprecation warning looks good.

I think we should also remove the link to the collapsable listbox example from:
* Scrollable Listbox Example
* Example Listboxes with Rearrangeable Options
* Listbox Example with Grouped Options

I'd like to discuss whether we note deprecation in the main document or remove the link. I'm leaning toward removing the link. We might also want to put something in the metadata, perhaps a data attribute on the H1, that would tell the indexing code to ignore it.

Also, what about adding "(Deprecated)" to the beginning of the page title tag and the start of the H1? Hmm, maybe that could be the indicator to the indexing script.

2021-05-04 18:55 UTC, a11ydoer commented
APG groupd made a decision to remove deprecated examples on May 4, 2021

2021-05-04 18:56 UTC, a11ydoer commented
@jongund will update APG example index page after @mcking65 merge this issue.

2021-05-06 22:08 UTC, mcking65 commented
Note to self:
1. Prepend `(Deprecated) ` to title tag and H1
2. 2. Remove link from main doc and other example pages

2021-06-29 19:07 UTC, jongund commented
@smhigley @mcking65 @a11ydoer 
The only review this pull request needs is editorial on the deprecation warning and testing if the updated link works.  This should only require two maybe three people.  The list of reviewers seems to accessibility testing on all of our platforms.   I suggest updated the list of reviewers on this pull request.

2021-06-29 19:17 UTC, jongund commented
@smhigley 
The name of the example file needs to change from `listbox-collapsible.html` to `listbox-select-only.html` to match the change in `aria-practices.html`.

2021-06-29 19:18 UTC, jongund requested changes
@smhigley 
I think this pull request should just delete the `listbox-collapsible.html` reference in `aria-practices.html` and not add the new reference to  `listbox-select-only.html`.

The pull request that creates `listbox-select-only.html` should make it's own changes to `aria-practices.html` and `listbox-collapsible.html` so the links actually work, otherwise as a reviewer it is confusing.

2021-07-01 17:43 UTC, smhigley commented
@jongund the added link is for the already-existing `combobox-select-only` example, and the links should work (or at least, they work fine for me in the preview). If everyone things it'd be better not to have any link there at all, I can remove it, but I think it makes sense to use this PR to decide what example links to include in the Listbox section.

2021-07-01 18:28 UTC, jongund commented
@smhigley 
The link was not working yesterday when I tested, it works today.

2021-07-01 18:29 UTC, jongund approved these changes

2021-08-30 07:00 UTC, mcking65 commented on examples/listbox/listbox-grouped.html
> +<title>(Deprecated) Listbox Example with Grouped Options | WAI-ARIA Authoring Practices 1.2</title>
Oops, right change in wrong file :) I'll push a fix for this.

2021-08-30 07:01 UTC, mcking65 commented on examples/listbox/listbox-grouped.html
> +  <h1>(Deprecated) Listbox Example with Grouped Options</h1>
I'll fix this one too

2021-08-30 07:12 UTC, mcking65 approved these changes
OK, Looks good now. Thank you @smhigley!

2021-08-30 07:18 UTC, merged