Disclosure: Distinguish the widget from the control
w3c/aria-practices pull request #1880
Opened 2021-04-27 21:29 UTC by jonathantneal

This PR updates the document to distinguish the disclosure **widget** from the disclosure **control**.

At first, the document refers to the _disclosure_ as the **button**, but then later refers to that button as the disclosure **control**.

---

Note: If **widget** is not the appropriate term, the disclosure examples [[1](https://w3c.github.io/aria-practices/examples/disclosure/disclosure-img-long-description.html)] [[2](https://w3c.github.io/aria-practices/examples/disclosure/disclosure-faq.html)] [[3](https://w3c.github.io/aria-practices/examples/disclosure/disclosure-navigation.html)] [[4](https://w3c.github.io/aria-practices/examples/disclosure/disclosure-navigation-hybrid.html)] refer to a disclosure as a **design pattern**.

2021-04-29 14:49 UTC, carmacleod approved these changes
+1
I think this does make it clearer. :)
Thanks, @jonathantneal !

2021-05-04 16:27 UTC, jonathantneal commented
Thanks, @carmacleod!

Is there anything else I can do to help keep this PR moving along, or to help get it placed into the right queue for additional approval or rejection? I’m unsure if there is more to the process that I should be doing.

I hope this ping is helpfully persistent, or rather that it is _not_ annoyingly impatient! 😄

2021-05-04 20:10 UTC, carmacleod commented
@jonathantneal 
Thanks for the ping!
I have requested a review from @mcking65

2021-05-13 07:34 UTC, mcking65 requested changes
@jonathantneal 

Thank you for the PR. The task force discussed it at this week's meeting.

We agree with the issue. We had two concerns with the proposal as is:
1. It didn't make it really clear that the disclosure widget has 2 elements.
2. The word "typically" implied the control could be something other than a button.

I have proposed some revisions to address these concerns. Please accept or revise them.

2021-05-13 07:34 UTC, mcking65 commented on aria-practices.html
> +        A disclosure is a widget used to disclose additional information or controls.
```suggestion
        A disclosure is a widget that enables content to be either collapsed (hidden) or expanded (visible).
```

2021-05-13 07:34 UTC, mcking65 commented on aria-practices.html
> +        Typically, a disclosure <a href="#button">button</a> controls the visibility of a section of content.
```suggestion
        It has two elements: a disclosure <a href="#button">button</a> and a section of content whose visibility is controlled by the button.
```

2021-05-13 07:34 UTC, mcking65 commented on aria-practices.html
>          When the controlled content is hidden, it is often styled as a typical push button with a right-pointing arrow or triangle to hint that activating the button will display additional content.
```suggestion
        When the controlled content is hidden, the button is often styled as a typical push button with a right-pointing arrow or triangle to hint that activating the button will display additional content.
```

2021-06-02 16:10 UTC, jonathantneal commented
@mcking65

Sorry for the delay. Thank you for discussing my PR for offering revisions. I’ve accepted all of them. Let me know if there is anything else I can do to help keep this PR moving along. 😄

2021-06-02 16:20 UTC, mcking65 approved these changes
@jonathantneal thank you for raising this issue and proposing the changes!

2021-06-02 16:23 UTC, merged