Landmark Example Pages: Updated related document references to latest docs
w3c/aria-practices pull request #1882
Opened 2021-04-29 21:55 UTC by jongund

2021-07-15 15:57 UTC, jnurthen commented on examples/landmarks/complementary.html
> +    <script type="text/javascript" src="https://cdn.disability.illinois.edu/skipto.min.js"></script>
Should the w3c docs have a dependency on this?

2021-08-29 18:16 UTC, mcking65 requested changes
Thank you @jongund for keeping this up to date. We clearly have an issue for the redesign project here. Because we are not using respec on these pages, we have the hard coded hrefs. We need to find a way to get rid of them in the redesign or these hrefs will need constant attention on a lot of pages.

I see an external dependency on UI CDN. Can you please remove that?

2021-08-29 18:16 UTC, mcking65 commented on examples/landmarks/HTML5.html
> +    <script type="text/javascript" src="https://cdn.disability.illinois.edu/skipto.min.js"></script>
We shouldn't have this external dependency

2021-08-29 18:16 UTC, mcking65 commented on examples/landmarks/at.html
> +    <script type="text/javascript" src="https://cdn.disability.illinois.edu/skipto.min.js"></script>
Same issue with external dependency on UI CDN

2021-08-29 18:16 UTC, mcking65 commented
@a11ydoer please review the visual aspects of this PR, especially screen shots.

2021-08-31 16:27 UTC, a11ydoer approved these changes
Screen shots of each screen reader look good! Thanks, @jongund!

2021-08-31 16:28 UTC, a11ydoer commented
@mcking65 This is ready for merge.

2021-09-06 23:28 UTC, jongund commented
@mcking65 
I updated the CDN reference to use a local version.

2021-10-04 07:15 UTC, mcking65 approved these changes

2021-10-04 07:22 UTC, merged