Combobox example with scroll into view of item referenced by aria-activedescendant
w3c/aria-practices pull request #2055
Opened 2021-10-05 23:03 UTC by jongund

[Preview Link](https://raw.githack.com/w3c/aria-practices/combobox-both-scroll-to/examples/combobox/combobox-autocomplete-both.html)

2021-10-05 23:04 UTC, jongund commented
@mcking65 
I have updated the combobox example to include a scroll into view feature.

2021-10-06 04:47 UTC, JAWS-test commented
Thank you for the quick change. It works correctly now

2021-10-10 18:37 UTC, mcking65 requested changes

2021-10-10 18:37 UTC, mcking65 commented on examples/combobox/combobox-autocomplete-both.html
> +              To make it easier to perceive focus of the textbox/button a 2px focus ring is placed around the <code>input</code> and <code>button</code> elements with 2 pixels of space between the fo
```suggestion
              To make it easier to perceive focus of the textbox and button, focus creates a 2 pixel focus ring around the <code>input</code> and <code>button</code> elements with 2 pixels of space between the focus ring and the combobox.
```

2021-10-10 18:37 UTC, mcking65 commented on examples/combobox/combobox-autocomplete-both.html
> +              To make it easier to perceive the selected listbox option a 2px border is placed above and below option.
```suggestion
              To make it easier to perceive the selected listbox option, selection creates a 2 pixel border above and below the option.
```

2021-10-10 23:56 UTC, jongund commented on examples/combobox/combobox-autocomplete-both.html
> +              To make it easier to perceive focus of the textbox/button a 2px focus ring is placed around the <code>input</code> and <code>button</code> elements with 2 pixels of space between the fo
updated per your suggestion

2021-10-10 23:58 UTC, jongund commented
@mcking65 
I did some updating of keyboard focus styling to support high contrast modes, part of the changes required using the `onblur` event to remove a `focus` class from the container element to remove the border around the textbox and button.

2021-10-31 06:52 UTC, mcking65 commented
Accessibility review was completed during last telecon. Merging.

2021-10-31 06:57 UTC, merged