Implement 2418 task 8
w3c/aria-practices pull request #2450
Opened 2022-08-29 19:20 UTC by alflennik

See https://github.com/w3c/aria-practices/issues/2418 for more information about the task. Note that the build will fail until the changes on the move-examples-6 branch (https://github.com/w3c/aria-practices/pull/2441) are approved and merged.

2022-09-04 18:30 UTC, mcking65 requested changes
Tested, working great!

However, I think we need to do two more things with this PR.

1. Delete the content/index.html file generated by the old version of the script.
2. Change content of scripts/reference-tables.template to match what is in prod on the WAI site. One of our goals of the restructure is for all content in prod to be in the aria-practices repo. The jekyll build should not add or modify content.

2022-09-07 18:00 UTC, alflennik commented
@mcking65 Thanks for the feedback, and I implemented the fixes. I had indeed missed the previous index.html file, thanks for noticing it. I also updated the copy to match the production site.

2022-09-20 15:12 UTC, mcking65 requested changes
Looking good; just one more thing. I think we need some edits to the head in the template. I don't know which script and css is needed. We should think about both what is needed in prod and what helps people when viewing the content locally in clones of the repo.

2022-09-20 15:12 UTC, mcking65 commented on scripts/reference-tables.template
>    <script src="js/app.js"></script>
The paths on the file refs in the script and css don't appear correct

2022-09-22 18:17 UTC, alflennik commented
@mcking65 Thanks again for pointing out the broken link, I fixed it and several other broken links on this page, and now the JS and CSS running on this page are the same as the other example pages.

2022-09-23 16:08 UTC, mcking65 approved these changes

2022-09-23 16:09 UTC, merged